### ISSUE TITLE
Apply "_count" param over included resources in requests

### ISSUE THREAD

**Issue by BPierrick** [arkhn/warehouse-api#148]
## Problem
We need to request all encounters and patients linked to those encounters (in Cohort360 for instance)
The '_count' argument is applied to only the requested encounters, ant not the linked patients.

Request example: `/Encounter?service-provider=${serviceId}&_include=Encounter:subject&_count=10000`

## Description
This feature would allow to request more linked resources by applying the _count argument over all requested resources and its included resources

## Alternatives
In this particular case, an alternative would be to loop over each encounters matching the serviceId to extract their subject id, and then perform api calls on Patients resources with those Ids.
It could easily add a lot of subsequent api calls.

**Comment by nriss** [comment]
After checking the [zulip chat](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Group.2Emember.20queries), I think _count should not influence the _include

I think that instead of doing this request:
/Encounter?service-provider=${serviceId}&_include=Encounter:subject&_count=10000

You should do two requests:
* A first one to get encounters /Encounter?service-provider=${serviceId}&_count=10000
* A second one to get the associated patients: /Patient?_has:Encounter:subject:service-provider=${serviceId}&_count=10000
